services:
  docs:
    container_name: docs
    image: ghcr.io/mrcodageht/mrcodageht/courses/docs:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs.rule=Host(`docs.app.mrccommunity.com`)"
      - "traefik.http.services.docs.loadbalancer.server.port=80"
    networks:
      - traefik-proxy-network
networks:
  traefik-proxy-network:
    external: true