name: Deploiement
description: Action pour effectuer un deploiement sur un serveur

inputs: 
  use-tailscale: 
    description: ce parametre permet de specifier si on doit acceder via un reseau tailscale sur le vps
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - 
      name: verification des parametres
      shell: bash
      run: |
        echo "use_tailscale => ${{ inputs.use_tailscale }}"

    