name: Utilisation d'action perso

on: 
  push:
    branches: ['main']
  
jobs:
  update:
    runs-on: ubuntu-latest
    env:
      HOST: vpn
      SECRET_KEY: ${{ secrets.SSH_KEY_VPS }}
      USER_VPS: ${{ vars.VPS_USER }}
      DEST_PATH: /home/${{ vars.VPS_USER }}/actions

    steps:
      - run: echo mise a jour du projet ${{ github.repository }}
      
      
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{secrets.TS_OAUTH_CLIENT_SECRET}}
          tags: tag:workflow
      
      - name: checkout du repo
        uses: actions/checkout@v6

      - uses: mrcodageht/courses/actions/deploy@main
        with:
          host: $HOST
          secret-key: $SECRET_KEY
          user: $USER_VPS
          dest-path: $DEST_PATH
          docker-password: ${{ secrets.GITHUB_TOKEN }}
          



          

