name: ma premiere action

on: push

# Declaration des variables avec un scope global
env:
  VAR_1: from workflow

jobs:
  checkout:
    env: 
      VAR_2: from jobs
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        env:
          FIRSTNAME: Wesner
          VAR_3: from step
        run: echo "Hello $FIRSTNAME"

      - name: Recuperation du depot courant
        uses: actions/checkout@v6
        run: ls
        run: echo ${{ github.workspace }}

      - name: Recuperation du depot ftp module
        uses: actions/checkout@v6
        with:
          repository: 'mrcodageht/ftp-module'
        run: ls

      - name: step event name
        run: echo ${{ github.event_name }}

      - name: affichage des valeurs des variables
        run: echo "variable 1 => $VAR_1"
        run: echo "variable 2 => $VAR_2"
        run: echo "variable 3 => $VAR_3"
        run: echo "Fisrtname => $FIRSTNAME"
