name: utilisation des commandes workflow

on: 
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo ::notice::Un message info
                echo ::error::Message erreur
                echo ::warning::Message avertissement
