name: utilisation des commandes workflow

on: 
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo ::notice::Un message d'info
                echo ::error::Message d'erreur
                echo ::warning::Message d'avertissement
